
catpuns = {
    ['for real'] = 'fur real',
    whenever = 'whenefur',
    possible = 'pawsible',
    athletic = 'cathletic',
    awful = 'clawful',
    perfect = 'purrfect',
    feeling = 'feline',
    clever = 'clawver',
    tale = 'tail',
    perhaps = 'purrhaps',
    possibility = 'pawsibility',
    friend = 'furend',
    pretty = 'purrty',
    literate = 'litterate',
    hysterical = 'hissterical',
    now = 'meow',
    pause = 'paws',
    familiar = 'furmilliar',
    awesome = 'pawsome',
    forget = 'furget',
    attitude = 'catitude',
    forever = 'furrever',
    appaling = 'apawling',
    radical = 'radiclaw',
    music = 'mewsic',
    inferior = 'infurior',
    metaphorically = 'metafurkitty',
    --you = 'mew',
    minimum = 'mewnimum',
    himself = 'hissself',
    misery = 'mewsery',
    forward = 'furward',
    perceive = 'purceive',
    very = 'furry',
}


