
biome_cave = Def('cave',{name='cave'},'biome')
biome_cave.tilecolor = "#9e9e9e"
biome_cave.needs_costs_food = 20
biome_cave.images = {
    "/img/rpg/world/zones/cave0.png",
    "/img/rpg/world/zones/cave1.png",
    "/img/rpg/world/zones/cave2.png",
    "/img/rpg/world/zones/cave3.png",
    "/img/rpg/world/zones/cave4.png",
    "/img/rpg/world/zones/cave5.png",
    "/img/rpg/world/zones/cave6.png",
    "/img/rpg/world/zones/cave7.png",
    "/img/rpg/world/zones/cave8.png",
    "/img/rpg/world/zones/cave9.png",
    "/img/rpg/world/zones/cave10.png",
    "/img/rpg/world/zones/cave11.png",
    "/img/rpg/world/zones/cave12.png",
    "/img/rpg/world/zones/cave13.png",
    "/img/rpg/world/zones/cave14.png",
    "/img/rpg/world/zones/cave15.png",
    "/img/rpg/world/zones/cave16.png",
    "/img/rpg/world/zones/cave17.png",
    "/img/rpg/world/zones/cave18.png",
    "/img/rpg/world/zones/cave19.png",
    "/img/rpg/world/zones/cave20.png",
    "/img/rpg/world/zones/cave21.png",
    "/img/rpg/world/zones/cave22.png",
    "/img/rpg/world/zones/cave23.png",
    "/img/rpg/world/zones/cave24.png",
    "/img/rpg/world/zones/cave25.png",
    "/img/rpg/world/zones/cave26.png",
    "/img/rpg/world/zones/cave27.png",
    "/img/rpg/world/zones/cave28.png", 
}
