
biome_grassland = Def('grassland',{name='grassland'},'biome')
biome_grassland.tilecolor = "#98d91b"
biome_grassland.images = {
    "/img/rpg/world/zones/grassland_plains.png",
    "/img/rpg/world/zones/grassland_plains2.png",
    "/img/rpg/world/zones/grassland_plains3.png",
    "/img/rpg/world/zones/grassland_plains4.png",
    "/img/rpg/world/zones/grassland_plains5.png",
    "/img/rpg/world/zones/grassland_plains6.png",
    "/img/rpg/world/zones/grassland_hills.png",
    "/img/rpg/world/zones/grassland_hills2.png",
    "/img/rpg/world/zones/grassland_hills3.png",
    "/img/rpg/world/zones/grassland_hills4.png",
    "/img/rpg/world/zones/grassland_hills5.png",
    "/img/rpg/world/zones/grassland_hills6.png",
    "/img/rpg/world/zones/grassland_hills7.png",
}
biome_grassland.nearcoast = {
    "/img/rpg/world/zones/coast0.png", 
    "/img/rpg/world/zones/coast1.png", 
    "/img/rpg/world/zones/coast2.png", 
    "/img/rpg/world/zones/coast3.png", 
    "/img/rpg/world/zones/coast4.png", 
    "/img/rpg/world/zones/coast5.png", 
    "/img/rpg/world/zones/coast6.png", 
    "/img/rpg/world/zones/coast7.png", 
    "/img/rpg/world/zones/coast8.png", 
    "/img/rpg/world/zones/coast9.png", 
    "/img/rpg/world/zones/coast10.png", 
    "/img/rpg/world/zones/coast11.png", 
    "/img/rpg/world/zones/coast12.png", 
    "/img/rpg/world/zones/coast13.png", 
    "/img/rpg/world/zones/coast14.png", 
    "/img/rpg/world/zones/coast15.png", 
    "/img/rpg/world/zones/coast16.png", 
    "/img/rpg/world/zones/coast17.png", 
    "/img/rpg/world/zones/coast18.png", 
    "/img/rpg/world/zones/coast19.png", 
    "/img/rpg/world/zones/coast20.png", 
    "/img/rpg/world/zones/coast21.png", 
    "/img/rpg/world/zones/coast22.png", 
    "/img/rpg/world/zones/coast23.png", 
    "/img/rpg/world/zones/coast24.png", 
    "/img/rpg/world/zones/coast25.png", 
    "/img/rpg/world/zones/coast26.png", 
    "/img/rpg/world/zones/coast27.png", 
    "/img/rpg/world/zones/coast28.png", 
}
biome_grassland.withroad = {
    "/img/rpg/world/zones/grassland_road0.png", 
    "/img/rpg/world/zones/grassland_road1.png", 
    "/img/rpg/world/zones/grassland_road2.png", 
    "/img/rpg/world/zones/grassland_road3.png", 
    "/img/rpg/world/zones/grassland_road4.png", 
    "/img/rpg/world/zones/grassland_road5.png", 
    "/img/rpg/world/zones/grassland_road6.png", 
    "/img/rpg/world/zones/grassland_road7.png", 
    "/img/rpg/world/zones/grassland_road8.png", 
    "/img/rpg/world/zones/grassland_road9.png", 
    "/img/rpg/world/zones/grassland_road10.png", 
}


biome_steppe = Def('steppe',{name='steppe'},'biome')
biome_steppe.tilecolor = "#bcd240"
biome_steppe.images = {
    "/img/rpg/world/zones/steppe0.png",
    "/img/rpg/world/zones/steppe1.png",
    "/img/rpg/world/zones/steppe2.png",
    "/img/rpg/world/zones/steppe3.png",
    "/img/rpg/world/zones/steppe4.png",
    "/img/rpg/world/zones/steppe5.png",
    "/img/rpg/world/zones/steppe6.png",
    "/img/rpg/world/zones/steppe7.png",
    "/img/rpg/world/zones/steppe8.png",
    "/img/rpg/world/zones/steppe9.png",
    "/img/rpg/world/zones/steppe10.png",
    "/img/rpg/world/zones/steppe11.png",
    "/img/rpg/world/zones/steppe12.png",
    "/img/rpg/world/zones/steppe13.png",
    "/img/rpg/world/zones/steppe14.png",
    "/img/rpg/world/zones/steppe15.png",
    "/img/rpg/world/zones/steppe16.png",
    "/img/rpg/world/zones/steppe17.png",
    "/img/rpg/world/zones/steppe18.png",
    "/img/rpg/world/zones/steppe19.png",
}
biome_steppe.withroad = {
    "/img/rpg/world/zones/steppe_road0.png",
    "/img/rpg/world/zones/steppe_road1.png",
    "/img/rpg/world/zones/steppe_road2.png",
    "/img/rpg/world/zones/steppe_road3.png",
    "/img/rpg/world/zones/steppe_road4.png",
}
