biome_tectonic_desert = Def('tectonic_desert',{name='tectonic desert'},'biome') 
biome_tectonic_desert.tilecolor='#83431c'
biome_tectonic_desert.images = {
    "/img/rpg/world/zones/tectonic_desert1.png", 
    "/img/rpg/world/zones/tectonic_desert2.png", 
    "/img/rpg/world/zones/tectonic_desert3.png", 
    "/img/rpg/world/zones/tectonic_desert4.png", 
    "/img/rpg/world/zones/tectonic_desert5.png", 
    "/img/rpg/world/zones/tectonic_desert6.png", 
    "/img/rpg/world/zones/tectonic_desert7.png", 
    "/img/rpg/world/zones/tectonic_desert8.png",  
    "/img/rpg/world/zones/tectonic_desert9.png", 
    "/img/rpg/world/zones/tectonic_desert10.png", 
    "/img/rpg/world/zones/tectonic_desert11.png", 
    "/img/rpg/world/zones/tectonic_desert12.png", 
    "/img/rpg/world/zones/tectonic_desert14.png", 
    "/img/rpg/world/zones/tectonic_desert15.png", 
    "/img/rpg/world/zones/tectonic_desert16.png",  
    "/img/rpg/world/zones/tectonic_desert17.png", 
    "/img/rpg/world/zones/tectonic_desert18.png",  
    "/img/rpg/world/zones/tectonic_desert19.png", 
    "/img/rpg/world/zones/tectonic_desert20.png", 
    "/img/rpg/world/zones/tectonic_desert21.png", 
    "/img/rpg/world/zones/tectonic_desert22.png", 
    "/img/rpg/world/zones/tectonic_desert24.png", 
}
biome_tectonic_desert_active = Def('tectonic_desert_active',{name='active tectonic desert'},'biome')
biome_tectonic_desert_active.tilecolor='#962c13'
biome_tectonic_desert_active.images = {
    "/img/rpg/world/zones/tectonic_desert_active1.png", 
    "/img/rpg/world/zones/tectonic_desert_active2.png", 
    "/img/rpg/world/zones/tectonic_desert_active3.png", 
    "/img/rpg/world/zones/tectonic_desert_active4.png",  
    "/img/rpg/world/zones/tectonic_desert_active5.png", 
    "/img/rpg/world/zones/tectonic_desert_active6.png", 
    "/img/rpg/world/zones/tectonic_desert_active7.png", 
    "/img/rpg/world/zones/tectonic_desert_active8.png", 
    "/img/rpg/world/zones/tectonic_desert_active9.png", 
    "/img/rpg/world/zones/tectonic_desert_active10.png", 
    "/img/rpg/world/zones/tectonic_desert_active11.png", 
    "/img/rpg/world/zones/tectonic_desert_active12.png", 
    "/img/rpg/world/zones/tectonic_desert_active14.png", 
    "/img/rpg/world/zones/tectonic_desert_active15.png", 
    "/img/rpg/world/zones/tectonic_desert_active16.png",  
} 
